import os
import time

print ("_______________________________________________________")
print()
print()
print()
print ("""\033[96m 
**𝐈𝐍𝐈 𝐓𝐖𝐄𝐀𝐊 𝐃𝐈𝐉𝐀𝐌𝐈𝐍 𝐖𝐎𝐑𝐄𝐊 𝐘𝐀 𝐊𝐎𝐍𝐓𝐎𝐋𝐋𝐋𝐋𝐋𝐋𝐋𝐋**""")
print("                        [*]  YOUTUBE : PIKUTSUU CH STREAMER KECIL  🤏        ")
print()
print()
print()
print()
print()
print()
print()
print()
print("\033[96m      **PILIH GAMENYA DULU YA MEMEG** ")
print()
print()
print()
print()
print("  _________________________")
print("  |   [*] MOBEL ENTOD  |")
print()
print()
print("  |   [*] BABAJI MOBEL         |")
print()
print()
print("  |   [*] FORNAITI        |")
print()
print()
print("  |   [*] API GRATIS MAX        |")
print()
print()
print("  |   [*] GAME 4NO        |")
print()
print()
print("  |   [*] CHROME BUAT BUKA BOKEP        |")
print("  _________________________")
print()
print()
print()
print()
print()
print()
print()
print()
input("\033[0m[*] SEDANG MENYUNTIKKAN VAKSIN CORONA KEDALAM GAME, BIAR GAMENYA BEBAS KOPID DAN BISA BERAKTIFITAS LANCAR :")
print()
print()
print()
print("\033[92m[*] PILIH FPS NYA BUJANG, KARENA SUDAH DI TANAMI RTX 4090 TI SUPER JADI BISA FPS TINGGI ")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Please wait...")
time.sleep(1)
print("[*] Done 👍 ")
time.sleep(3)
print()
print()
print()
print("\033[96m      **FITUR RTX DAN PILIH FPS DISINI YA JEMBOED** ")
print()
print()
print()
print()
print("  ___________________")
print("  |   [*] 99999999 FPS + RAY TRACING ON |")
print()
print()
print("  |   [*] 69696969 FPS + WEBVIEW BIAR BOKEP LEBIH JERNIH KARENA MAKE VULKAN  |")
print()
print()
print("  |   [*] 10000000 FPS + NVIDIA REFLEX BIAR AIM PRO MACAM ZUXXY |")
print()
print()
print("  |   [*] ACIL OUT HEHE |")
print("  __________________")
print()
print()
print()
input("\033[0mSelect The better Fps : ")
time.sleep(1)
print("\033[96m[*] Downloading (100GB size)... ")
time.sleep(1)
print("[*] Please wait a few seconds...")
time.sleep(5)
print()
print("[*] Success download")
time.sleep(1)
print("[*] SEKARANG HP LU UDAH DITANEMIN SCRIPT RTX 4090 TI SUPER + UDAH SUPPORT MAEN SEMUA GAME STEAM TANPA LAG + STREAMING BOKEP LANCAR")
time.sleep(2)
print()
print("3")
time.sleep(1)
print("2")
time.sleep(1)
print("1")
time.sleep(3)
print("\033[91m[*] MAKASIH ACIL UDAH OUT HEHE")